package br.org.cgee.gephi.statistics;

import java.util.List;
import javax.swing.DefaultListModel;
import org.openide.util.NbBundle;

/**
 * Settings panel for the {@link AverageEuclideanDistance} statistic. It uses
 * a nice <code>JXHeader</code> at the top of the panel. 
 * 
 * @author Mathieu Bastian
 */
public class CorrelationStatisticsPanel extends javax.swing.JPanel {
    
    /** Creates new form AverageEuclideanDistancePanel */
    public CorrelationStatisticsPanel() {
        initComponents();
    }
    
    public void setStatisticsType(DelegateCorrelationStatistics.CorrelationType type) {
        String typeIndex = type.name().toLowerCase();
        jXHeader1.setTitle(NbBundle.getMessage(CorrelationStatisticsPanel.class, "CorrelationPanel.title."+typeIndex));
        jXHeader1.setDescription(NbBundle.getMessage(CorrelationStatisticsPanel.class, "CorrelationPanel.description."+typeIndex));
    }
    
    public void setAttributeList(List<String> attributes) {
        DefaultListModel<String> listModel = new DefaultListModel<String>();
        for (String attribute : attributes) {
            listModel.addElement(attribute);
        }
        jList1.setModel(listModel);
        jList2.setModel(listModel);
    }
    
    public void setAttributes(String attribute1, String attribute2, boolean ignoreMissing1, boolean ignoreMissing2) {
        jList1.setSelectedValue(attribute1, true);
        jList2.setSelectedValue(attribute2, true);
        jRadioButtonAtt1IgnoreMissing.setSelected(ignoreMissing1);
        jRadioButtonAtt1TreatAsZero.setSelected(!ignoreMissing1);
        jRadioButtonAtt2IgnoreMissing.setSelected(ignoreMissing2);
        jRadioButtonAtt2TreatAsZero.setSelected(!ignoreMissing2);
    }
    
    public String getAttribute1() {
        return (String) jList1.getSelectedValue();
    }
    
    public String getAttribute2() {
        return (String) jList2.getSelectedValue();
    }
    
    public boolean isIgnoreMissingAttribute1() {
        return jRadioButtonAtt1IgnoreMissing.isSelected();
    }

    public boolean isIgnoreMissingAttribute2() {
        return jRadioButtonAtt2IgnoreMissing.isSelected();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupAttribute1Missing1 = new javax.swing.ButtonGroup();
        buttonGroupAttributeMissing2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jXHeader1 = new org.jdesktop.swingx.JXHeader();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonAtt1TreatAsZero = new javax.swing.JRadioButton();
        jRadioButtonAtt1IgnoreMissing = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jRadioButtonAtt2TreatAsZero = new javax.swing.JRadioButton();
        jRadioButtonAtt2IgnoreMissing = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(556, 307));

        jLabel1.setText(org.openide.util.NbBundle.getMessage(CorrelationStatisticsPanel.class, "CorrelationStatisticsPanel.jLabel1.text")); // NOI18N

        jXHeader1.setDescription("Description"); // NOI18N
        jXHeader1.setTitle("Correlation"); // NOI18N

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel3.setText(org.openide.util.NbBundle.getMessage(CorrelationStatisticsPanel.class, "CorrelationStatisticsPanel.jLabel3.text")); // NOI18N

        buttonGroupAttribute1Missing1.add(jRadioButtonAtt1TreatAsZero);
        jRadioButtonAtt1TreatAsZero.setText(org.openide.util.NbBundle.getMessage(CorrelationStatisticsPanel.class, "CorrelationStatisticsPanel.jRadioButtonAtt1TreatAsZero.text")); // NOI18N

        buttonGroupAttribute1Missing1.add(jRadioButtonAtt1IgnoreMissing);
        jRadioButtonAtt1IgnoreMissing.setText(org.openide.util.NbBundle.getMessage(CorrelationStatisticsPanel.class, "CorrelationStatisticsPanel.jRadioButtonAtt1IgnoreMissing.text")); // NOI18N
        jRadioButtonAtt1IgnoreMissing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAtt1IgnoreMissingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonAtt1TreatAsZero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonAtt1IgnoreMissing)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAtt1TreatAsZero)
                    .addComponent(jRadioButtonAtt1IgnoreMissing)))
        );

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        buttonGroupAttributeMissing2.add(jRadioButtonAtt2TreatAsZero);
        jRadioButtonAtt2TreatAsZero.setText(org.openide.util.NbBundle.getMessage(CorrelationStatisticsPanel.class, "CorrelationStatisticsPanel.jRadioButtonAtt2TreatAsZero.text")); // NOI18N
        jRadioButtonAtt2TreatAsZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAtt2TreatAsZeroActionPerformed(evt);
            }
        });

        buttonGroupAttributeMissing2.add(jRadioButtonAtt2IgnoreMissing);
        jRadioButtonAtt2IgnoreMissing.setText(org.openide.util.NbBundle.getMessage(CorrelationStatisticsPanel.class, "CorrelationStatisticsPanel.jRadioButtonAtt2IgnoreMissing.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(CorrelationStatisticsPanel.class, "CorrelationStatisticsPanel.jLabel2.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButtonAtt2TreatAsZero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonAtt2IgnoreMissing))
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAtt2TreatAsZero)
                    .addComponent(jRadioButtonAtt2IgnoreMissing))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jXHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonAtt2TreatAsZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAtt2TreatAsZeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAtt2TreatAsZeroActionPerformed

    private void jRadioButtonAtt1IgnoreMissingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAtt1IgnoreMissingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAtt1IgnoreMissingActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupAttribute1Missing1;
    private javax.swing.ButtonGroup buttonGroupAttributeMissing2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonAtt1IgnoreMissing;
    private javax.swing.JRadioButton jRadioButtonAtt1TreatAsZero;
    private javax.swing.JRadioButton jRadioButtonAtt2IgnoreMissing;
    private javax.swing.JRadioButton jRadioButtonAtt2TreatAsZero;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXHeader jXHeader1;
    // End of variables declaration//GEN-END:variables
}
